language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '7'
before_script:
  - npm prune
script:
  - npm run test:single
  - npm run build-storybook
after_success:
  - npm run semantic-release
deploy:
  provider: surge
  project: ./storybook-static/
  domain: react-animation-components.surge.sh 
branches:
  only: 
    - master
