language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '7'
before_script:
  - npm prune
script:
  - npm run test:single
after_success:
  - npm run semantic-release
before_deploy:
  - npm run build-storybook && ls
deploy:
  skip_cleanup: true
  provider: surge
  project: ./storybook-static
  domain: react-animation-components.surge.sh
  on:
    tags: true 
branches:
  only: 
    - master
