language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '7'
before_script:
  - npm prune
script:
  - npm run test:single
after_success:
  - npm run semantic-release
branches:
  only: 
    - master
